package com.studio.ai;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import androidx.media3.transformer.Transformer;import org.json.*;import java.io.File;import java.util.*;

public class TimelineActivity extends Activity {
 SharedPreferences prefs;LinearLayout root,content;JSONObject video,timeline;String project,style;Transformer transformer;
 final int BG=Color.rgb(9,11,15),CARD=Color.rgb(19,23,30),MUTED=Color.rgb(151,160,174),GREEN=Color.rgb(124,255,178);
 int dp(float x){return Math.round(x*getResources().getDisplayMetrics().density);} GradientDrawable bg(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
 TextView tx(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));v.setGravity(Gravity.END);v.setTextDirection(View.TEXT_DIRECTION_RTL);v.setPadding(dp(4),dp(4),dp(4),dp(4));return v;}
 Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setSingleLine(true);b.setTextColor(Color.rgb(5,20,13));b.setTypeface(null,Typeface.BOLD);b.setBackground(bg(GREEN,16));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("studio",MODE_PRIVATE);project=getIntent().getStringExtra("project");style=getIntent().getStringExtra("style");try{video=new JSONObject(getIntent().getStringExtra("video"));}catch(Exception e){finish();return;}timeline=EditTimelineStore.load(prefs,project,style,video);render();}
 void render(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(BG);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setPadding(dp(18),dp(30),dp(18),dp(30));sc.addView(root);setContentView(sc);root.addView(tx("STUDIO / AI",12,GREEN,true));root.addView(tx("التايملاين القابل للتحرير",27,Color.WHITE,true));root.addView(tx(video.optString("name","فيديو")+" • "+format(EditTimelineStore.duration(timeline)),14,MUTED,false));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content);card("تحرير حقيقي للخطة","القص والتقسيم والترتيب والسرعة والاستبعاد محفوظة. الدفعة 14 تستطيع الآن تنفيذ هذه الخطة فعليًا إلى MP4 جديد؛ الملف الأصلي يبقى كما هو.");JSONArray a=timeline.optJSONArray("clips");for(int i=0;a!=null&&i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c!=null)clipCard(i,c);}Button render=button("▶ تنفيذ الخطة ورندر MP4");LinearLayout.LayoutParams rr=new LinearLayout.LayoutParams(-1,dp(58));rr.setMargins(0,dp(14),0,0);content.addView(render,rr);render.setOnClickListener(v->startRender(render));Button reset=button("إعادة بناء التايملاين من التحليل");LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(52));rp.setMargins(0,dp(10),0,0);content.addView(reset,rp);reset.setOnClickListener(v->{EditTimelineStore.reset(prefs,project,style,video);timeline=EditTimelineStore.load(prefs,project,style,video);render();});Button close=button("رجوع للمشروع");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(10),0,0);content.addView(close,p);close.setOnClickListener(v->finish());}
 void startRender(Button b){if(transformer!=null){toast("الرندر يعمل الآن");return;}b.setEnabled(false);b.setText("جارٍ الرندر…");try{File dir=new File(getExternalFilesDir(null),"renders");if(!dir.exists()&&!dir.mkdirs())throw new Exception("تعذر إنشاء مجلد الرندر");File out=new File(dir,"studio_"+System.currentTimeMillis()+".mp4");transformer=TimelineRenderer.render(this,video,timeline,out,new TimelineRenderer.Listener(){public void onCompleted(File f,androidx.media3.transformer.ExportResult r){transformer=null;runOnUiThread(()->{b.setEnabled(true);b.setText("▶ تنفيذ الخطة ورندر MP4");card("✅ اكتمل الرندر الحقيقي","تم إنشاء MP4 جديد فعليًا.\nالحجم: "+String.format(Locale.US,"%.1f MB",f.length()/1048576.0)+"\nالمسار الداخلي: "+f.getName()+"\nالتصدير/المشاركة للمستخدم ستكون في الدفعة 15.");});}public void onError(Exception e){transformer=null;runOnUiThread(()->{b.setEnabled(true);b.setText("▶ تنفيذ الخطة ورندر MP4");toast("فشل الرندر: "+(e.getMessage()==null?"خطأ في الوسائط":e.getMessage()));});}});}catch(Exception e){transformer=null;b.setEnabled(true);b.setText("▶ تنفيذ الخطة ورندر MP4");toast(e.getMessage()==null?"تعذر بدء الرندر":e.getMessage());}}
 void card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(12),dp(16),dp(12));c.setBackground(bg(CARD,16));c.addView(tx(a,17,Color.WHITE,true));c.addView(tx(b,13,MUTED,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,0);content.addView(c,p);}
 void clipCard(int index,JSONObject c){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(14));box.setBackground(bg(CARD,16));boolean enabled=c.optBoolean("enabled",true);long start=c.optLong("sourceStartMs"),end=c.optLong("sourceEndMs");box.addView(tx("لقطة "+(index+1)+(enabled?"":" • مستبعدة"),17,enabled?Color.WHITE:MUTED,true));box.addView(tx(format(start)+" → "+format(end)+"   •   "+format(end-start)+"   •   سرعة ×"+c.optDouble("speed",1),13,MUTED,false));String note=c.optString("note","");if(!note.isEmpty())box.addView(tx("ملاحظة: "+note,13,MUTED,false));LinearLayout r1=row(),r2=row();addAction(r1,enabled?"استبعاد":"استعادة",()->{EditTimelineStore.setEnabled(timeline,index,!enabled);save();});addAction(r1,"تقسيم",()->splitDialog(index,start,end));addAction(r1,"قص الحدود",()->trimDialog(index,start,end));addAction(r1,"السرعة",()->speedDialog(index));addAction(r2,"ملاحظة",()->noteDialog(index,note));addAction(r2,"↑ للأعلى",()->{if(EditTimelineStore.move(timeline,index,Math.max(0,index-1)))save();});addAction(r2,"↓ للأسفل",()->{JSONArray a=timeline.optJSONArray("clips");if(a!=null&&EditTimelineStore.move(timeline,index,Math.min(a.length()-1,index+1)))save();});box.addView(r1);box.addView(r2);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,0);content.addView(box,p);}
 LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.END);return r;} void addAction(LinearLayout row,String name,Runnable action){Button b=button(name);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(52),1);p.setMargins(dp(3),dp(10),dp(3),0);row.addView(b,p);b.setOnClickListener(v->action.run());}
 void splitDialog(int i,long s,long e){final EditText x=input(String.valueOf((s+e)/2000.0));new AlertDialog.Builder(this).setTitle("قسّم عند الثانية").setView(x).setPositiveButton("تقسيم",(d,w)->{try{long at=Math.round(Double.parseDouble(x.getText().toString())*1000);if(EditTimelineStore.split(timeline,i,at))save();else toast("نقطة التقسيم خارج اللقطة");}catch(Exception z){toast("قيمة غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void trimDialog(int i,long s,long e){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText a=input(String.valueOf(s/1000.0)),b=input(String.valueOf(e/1000.0));a.setHint("البداية بالثواني");b.setHint("النهاية بالثواني");l.addView(a);l.addView(b);new AlertDialog.Builder(this).setTitle("قص حدود اللقطة").setView(l).setPositiveButton("حفظ",(d,w)->{try{if(EditTimelineStore.trim(timeline,i,Math.round(Double.parseDouble(a.getText().toString())*1000),Math.round(Double.parseDouble(b.getText().toString())*1000)))save();else toast("حدود القص غير صحيحة");}catch(Exception z){toast("قيمة غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
 void speedDialog(int i){String[] x={"0.5×","1×","1.5×","2×"};double[] v={.5,1,1.5,2};new AlertDialog.Builder(this).setTitle("سرعة اللقطة").setItems(x,(d,w)->{EditTimelineStore.setSpeed(timeline,i,v[w]);save();}).show();}
 void noteDialog(int i,String old){EditText x=input(old);new AlertDialog.Builder(this).setTitle("ملاحظة اللقطة").setView(x).setPositiveButton("حفظ",(d,w)->{EditTimelineStore.setNote(timeline,i,x.getText().toString());save();}).setNegativeButton("إلغاء",null).show();}
 EditText input(String s){EditText e=new EditText(this);e.setText(s);e.setTextColor(Color.BLACK);e.setSelectAllOnFocus(true);return e;}void save(){EditTimelineStore.save(prefs,project,style,video,timeline);render();}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}String format(long ms){long sec=Math.max(0,ms)/1000;return String.format(Locale.US,"%d:%02d",sec/60,sec%60);}
 @Override protected void onDestroy(){if(transformer!=null){transformer.cancel();transformer=null;}super.onDestroy();}
}
