package com.studio.ai;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

public class TimelineActivity extends Activity {
    SharedPreferences prefs; LinearLayout root,content; JSONObject video,timeline; String project,style;
    final int BG=Color.rgb(9,11,15),CARD=Color.rgb(19,23,30),MUTED=Color.rgb(151,160,174),GREEN=Color.rgb(124,255,178);
    int dp(float x){return Math.round(x*getResources().getDisplayMetrics().density);}
    GradientDrawable bg(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
    TextView tx(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));v.setGravity(Gravity.END);v.setTextDirection(View.TEXT_DIRECTION_RTL);v.setPadding(dp(4),dp(4),dp(4),dp(4));return v;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(5,20,13));b.setTypeface(null,Typeface.BOLD);b.setBackground(bg(GREEN,16));return b;}
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("studio",MODE_PRIVATE);project=getIntent().getStringExtra("project");style=getIntent().getStringExtra("style");try{video=new JSONObject(getIntent().getStringExtra("video"));}catch(Exception e){finish();return;}timeline=EditTimelineStore.load(prefs,project,style,video);render();}
    void render(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(BG);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setPadding(dp(18),dp(28),dp(18),dp(28));sc.addView(root);setContentView(sc);root.addView(tx("STUDIO / AI",12,GREEN,true));root.addView(tx("التايملاين القابل للتحرير",27,Color.WHITE,true));root.addView(tx(video.optString("name","فيديو")+" • "+format(EditTimelineStore.duration(timeline)),14,MUTED,false));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content);card("تحرير حقيقي للخطة","القص والتقسيم والترتيب والسرعة والحذف هنا تُحفظ كخطة تحرير فعلية. ملف الفيديو الأصلي لا يتغير في هذه الدفعة؛ الرندر يأتي في الدفعة 14.");JSONArray a=timeline.optJSONArray("clips");for(int i=0;a!=null&&i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c!=null)clipCard(i,c);}Button reset=button("إعادة بناء التايملاين من التحليل");content.addView(reset,new LinearLayout.LayoutParams(-1,dp(52)));reset.setOnClickListener(v->{EditTimelineStore.reset(prefs,project,style,video);timeline=EditTimelineStore.load(prefs,project,style,video);render();});Button close=button("رجوع للمشروع");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(10),0,0);content.addView(close,p);close.setOnClickListener(v->finish());}
    void card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(12),dp(16),dp(12));c.setBackground(bg(CARD,16));c.addView(tx(a,17,Color.WHITE,true));c.addView(tx(b,13,MUTED,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,0);content.addView(c,p);}
    void clipCard(int index,JSONObject c){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(12));box.setBackground(bg(CARD,16));boolean enabled=c.optBoolean("enabled",true);long start=c.optLong("sourceStartMs"),end=c.optLong("sourceEndMs");box.addView(tx("لقطة "+(index+1)+(enabled?"":" • مستبعدة"),17,enabled?Color.WHITE:MUTED,true));box.addView(tx(format(start)+" → "+format(end)+" • "+format(end-start)+" • سرعة ×"+c.optDouble("speed",1),13,MUTED,false));String note=c.optString("note","");if(!note.isEmpty())box.addView(tx("ملاحظة: "+note,13,MUTED,false));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.END);String[] names={enabled?"استبعاد":"استعادة","تقسيم","قص","سرعة","ملاحظة","↑","↓"};for(String name:names){Button b=button(name);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(44),1);bp.setMargins(dp(2),dp(8),dp(2),0);row.addView(b,bp);if(name.equals("استبعاد")||name.equals("استعادة"))b.setOnClickListener(v->{EditTimelineStore.setEnabled(timeline,index,!enabled);save();});else if(name.equals("تقسيم"))b.setOnClickListener(v->splitDialog(index,start,end));else if(name.equals("قص"))b.setOnClickListener(v->trimDialog(index,start,end));else if(name.equals("سرعة"))b.setOnClickListener(v->speedDialog(index));else if(name.equals("ملاحظة"))b.setOnClickListener(v->noteDialog(index,note));else if(name.equals("↑"))b.setOnClickListener(v->{if(EditTimelineStore.move(timeline,index,Math.max(0,index-1)))save();});else if(name.equals("↓"))b.setOnClickListener(v->{JSONArray a=timeline.optJSONArray("clips");if(a!=null&&EditTimelineStore.move(timeline,index,Math.min(a.length()-1,index+1)))save();});}box.addView(row);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,0);content.addView(box,p);}
    void splitDialog(int i,long s,long e){final EditText x=input(String.valueOf((s+e)/2000.0));new AlertDialog.Builder(this).setTitle("قسّم عند الثانية").setView(x).setPositiveButton("تقسيم",(d,w)->{try{long at=Math.round(Double.parseDouble(x.getText().toString())*1000);if(EditTimelineStore.split(timeline,i,at))save();else toast("نقطة التقسيم خارج اللقطة");}catch(Exception z){toast("قيمة غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
    void trimDialog(int i,long s,long e){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText a=input(String.valueOf(s/1000.0)),b=input(String.valueOf(e/1000.0));a.setHint("البداية بالثواني");b.setHint("النهاية بالثواني");l.addView(a);l.addView(b);new AlertDialog.Builder(this).setTitle("قص حدود اللقطة").setView(l).setPositiveButton("حفظ",(d,w)->{try{if(EditTimelineStore.trim(timeline,i,Math.round(Double.parseDouble(a.getText().toString())*1000),Math.round(Double.parseDouble(b.getText().toString())*1000)))save();else toast("حدود القص غير صحيحة");}catch(Exception z){toast("قيمة غير صحيحة");}}).setNegativeButton("إلغاء",null).show();}
    void speedDialog(int i){String[] x={"0.5×","1×","1.5×","2×"};double[] v={.5,1,1.5,2};new AlertDialog.Builder(this).setTitle("سرعة اللقطة").setItems(x,(d,w)->{EditTimelineStore.setSpeed(timeline,i,v[w]);save();}).show();}
    void noteDialog(int i,String old){EditText x=input(old);new AlertDialog.Builder(this).setTitle("ملاحظة اللقطة").setView(x).setPositiveButton("حفظ",(d,w)->{EditTimelineStore.setNote(timeline,i,x.getText().toString());save();}).setNegativeButton("إلغاء",null).show();}
    EditText input(String s){EditText e=new EditText(this);e.setText(s);e.setTextColor(Color.BLACK);e.setSelectAllOnFocus(true);return e;}
    void save(){EditTimelineStore.save(prefs,project,style,video,timeline);render();}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    String format(long ms){long sec=Math.max(0,ms)/1000;return String.format(Locale.US,"%d:%02d",sec/60,sec%60);}
}
