package com.studio.ai;
import android.content.Context;import android.net.Uri;import android.os.*;import androidx.annotation.OptIn;import androidx.media3.common.*;import androidx.media3.common.audio.SpeedProvider;import androidx.media3.common.util.UnstableApi;import androidx.media3.transformer.*;import org.json.*;import java.io.File;import java.util.*;
@OptIn(markerClass=UnstableApi.class)
public final class TimelineRenderer{
 public interface Listener{void onCompleted(File file,ExportResult result);void onError(Exception error);default void onProgress(int percent){}}
 private TimelineRenderer(){}
 public static Transformer render(Context context,JSONObject video,JSONObject timeline,File output,Listener listener)throws Exception{String source=video.optString("uri","");if(source.isEmpty())throw new IllegalArgumentException("مصدر الفيديو غير موجود");JSONArray clips=timeline.optJSONArray("clips");List<EditedMediaItem> items=new ArrayList<>();for(int i=0;clips!=null&&i<clips.length();i++){JSONObject c=clips.optJSONObject(i);if(c==null||!c.optBoolean("enabled",true))continue;long start=c.optLong("sourceStartMs",0),end=c.optLong("sourceEndMs",0);if(end<=start)continue;MediaItem media=new MediaItem.Builder().setUri(Uri.parse(source)).setClippingConfiguration(new MediaItem.ClippingConfiguration.Builder().setStartPositionMs(start).setEndPositionMs(end).build()).build();EditedMediaItem.Builder edit=new EditedMediaItem.Builder(media);double speed=c.optDouble("speed",1.0);if(Math.abs(speed-1.0)>.001)edit.setSpeed(constantSpeed((float)speed));items.add(edit.build());}if(items.isEmpty())throw new IllegalStateException("لا توجد لقطات مفعلة للرندر");if(output.exists()&&!output.delete())throw new IllegalStateException("تعذر استبدال ملف الرندر السابق");EditedMediaItemSequence seq=EditedMediaItemSequence.withAudioAndVideoFrom(items);Composition composition=new Composition.Builder(seq).build();Handler h=new Handler(Looper.getMainLooper());final boolean[] done={false};final Transformer[] holder=new Transformer[1];Transformer t=new Transformer.Builder(context).setVideoMimeType(MimeTypes.VIDEO_H264).setAudioMimeType(MimeTypes.AUDIO_AAC).addListener(new Transformer.Listener(){@Override public void onCompleted(Composition c,ExportResult r){done[0]=true;listener.onProgress(100);listener.onCompleted(output,r);}@Override public void onError(Composition c,ExportResult r,ExportException e){done[0]=true;listener.onError(e);}}).build();holder[0]=t;Runnable poll=new Runnable(){public void run(){if(done[0])return;try{ProgressHolder p=new ProgressHolder();int state=holder[0].getProgress(p);if(state==Transformer.PROGRESS_STATE_AVAILABLE)listener.onProgress(p.progress);}catch(Exception ignored){}if(!done[0])h.postDelayed(this,500);}};t.start(composition,output.getAbsolutePath());h.post(poll);return t;}
 private static SpeedProvider constantSpeed(final float speed){return new SpeedProvider(){public float getSpeed(long timeUs){return speed;}public long getNextSpeedChangeTimeUs(long timeUs){return C.TIME_UNSET;}};}
}
